import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shoppify",
  description: "Generated by create next app",
  icons: {
    icon: "../imgs/shopify.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-100 ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <ToastContainer position="bottom-right" />
        <Footer />
      </body>
    </html>
  );
}
